name: Release
on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Build
        run: |
          curl --location --output tsv https://github.com/jasondavis303/TimestampVersion/releases/latest/download/tsv
          chmod +x tsv
          ./tsv --xml-files Tagger/Tagger.csproj --env-file $GITHUB_ENV --verbose
          dotnet publish -r win-x64 -p:PublishSingleFile=true --no-self-contained -c release -o publish
          cd publish
          zip -m9 Tagger.zip Tagger.exe
          cd ..
          curl --location --output s3u  https://github.com/jasondavis303/s3u/releases/latest/download/s3u
          chmod +x s3u
          ./s3u --endpoint s3.us-central-1.wasabisys.com --access-key ${{ secrets.S3_KEY }} --access-secret ${{ secrets.S3_SECRET }} --source publish --bucket dustypig --target bin/tools --overwrite --verbose
