name: build
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Build
        run: |
          curl --location --output tsv https://github.com/jasondavis303/TimestampVersion/releases/latest/download/tsv
          chmod +x tsv
          ./tsv --xml-files Tagger/Tagger.csproj --env-file $GITHUB_ENV --verbose
          dotnet publish -r win-x64 -p:PublishSingleFile=true --no-self-contained -c release -o publish
          cd publish
          zip -m9 Tagger.zip Tagger.exe